sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - node_modules
    - src/main/webapp/bower_components
    - $HOME/.m2
before_install:
  - docker-compose up -d
  - docker ps -a
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
