language: java
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.3"
cache:
  directories:
    - node_modules
    - src/main/webapp/bower_components
    - $HOME/.m2
before_install:
    - $HOME/.nvm/nvm.sh
    - nvm install 5.5
    - nvm use 5.5
    - npm install -g grunt-cli
before_script:
    - psql -c 'create database silq2;' -U postgres
    - psql -U postgres -d silq2 -w -f sql/schema.sql
    - psql -U postgres -d silq2 -w -f sql/qualis_evento.sql
    - psql -U postgres -d silq2 -w -f sql/qualis_periodico.sql
script:
    - mvn test -B -D spring.profiles.active=travis
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
