language: node_js
node_js:
  - "4.2"
sudo: false
before_install: npm install -g grunt-cli
install: npm install
cache:
  directories:
    - node_modules
    - src/main/webapp/bower_components
    - $HOME/.m2
before_script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
