sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - postgresql
cache:
  directories:
    - node_modules
    - src/main/webapp/bower_components
    - $HOME/.m2
before_script:
    - psql -c 'create database silq2;' -U postgres
    - psql -U postgres -w -f sql/schema.sql
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
